# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: caea9bb1cd1eeed751818476654c2b09a9cb5f060bfa1df651d3f6b711f5662d7822c245c53d374587d53971cae58abcd9b7e416b3e333c99ef43c1f1f57e12a

test:
  secret_key_base: 5668cb24fc16d6c96dab64caeaf84c7f819617c333dce9d52f0ea29aa67ea5b103383d3bb2cb2d5fc4fad8d0507be13deb7ff3d41a35753c380575dfa0c209cd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
